# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 🚀 Lego Web-Components
email: vinyll+lego@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  🚀 Lego is a Web-components library to write reactive components in HTML.
  It is made lightweight & future-proof.
  Lego is a great alternative to Vue, React, Svelte, Lit and more accessible than
  extending native HTML elements.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: polight

# logo: "/assets/images/lego-logo.png"
logo_title: 🚀 Lego
search_title: "the Lego documentation"
footer_content: "Lego is <a href=https://github.com/polight/lego>open-source</a>. Distributed under <a href=\"https://github.com/polight/lego/tree/master/LICENSE.txt\">MIT license.</a>"
last_edit_timestamp: true
# color_scheme: dark
# destination: docs
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 5
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

collections:
  v1:
    permalink: "/v1/"
    output: true
  v2:
    permalink: "/v2/"
    output: true

just_the_docs:
  collections:
    v1:
      name: Documentation
      details: Version 1.8 stable
      banner: You are viewing the documentation for Lego v1. <a href="/v2/">Lego v2</a> is coming out! <a href="/v2/">Visit the new documentation</a>.
    v2:
      name: v2.0 - alpha
      details: Version 2.0 pre-release

# Build settings
## Commented out so Github can build. Uncomment for local development :shrug:
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
